//
// Copyright (C) 2010-2012 Javier Armendariz Silva, Naiara Garcia Royo
// Copyright (C) 2010-2012 Universidad Publica de Navarra
//
// This file is part of OBSModules.
//
// OBSModules is free software: you can redistribute it and/or modify
// it under the terms of the GNU Lesser General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
// 
// OBSModules is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Lesser General Public License for more details.
// 
// You should have received a copy of the GNU General Public License
// along with OBSModules.  If not, see <http://www.gnu.org/licenses/>.
//

#include <omnetpp.h>
#include "OBS_Burst.h"
#include <vector>
using namespace std;


//! Release the content of the burst when a burst finish message arrives.
class OBS_BurstDisassembler : public cSimpleModule{
   protected:
      /* Statistics */
      cOutVector fakeBursts; //!< Store information here if a burst generated by OBS_FileBurstifier is received.
      cOutVector VlistSize; //!< Burst list size vector.
      int listSize; //!< Burst list size.
      int recvBursts; //!< Received bursts counter.

      list<OBS_Burst*> receivedBursts; //!< Received bursts queue.

      //! Initializer of data structures and statistics.
      virtual void initialize();
      //! Incoming message handler.
      virtual void handleMessage(cMessage *msg);
      //! Record scalars.
      virtual void finish();
   public:
      //! Clean up recvBurst.
      virtual ~OBS_BurstDisassembler();
};
